version: '3.9'

services:
#  database
  postgres:
    image: postgres:15.0
    restart: always
    ports:
      - '5432:5432'
    container_name: postgres-server
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=safetylink
  scylla-1:
    image: scylladb/scylla
    restart: always
    ports:
      - '9042:9042'
    container_name: scylla-server
    command: --broadcast-address 127.0.0.1 --listen-address 0.0.0.0 --broadcast-rpc-address 127.0.0.1 --smp 1 --cqlsh
  #  message queue
  rabbitMQ:
    image: rabbitmq:3.9-management-alpine
    restart: always
    ports:
      - '15672:15672'
      - '5672:5672'
    container_name: rabbitmq-server
  # observation and tracing
  open-telemetry-collector:
    image: otel/opentelemetry-collector-contrib:0.70.0
    container_name: otel-collector
    restart: unless-stopped
    command: [ "--config=/etc/otelcol-config.yml" ]
    env_file:
      - ../.env.local
    volumes:
      - ../config/otelcol-config.yml:/etc/otelcol-config.yml
    ports:
      - "4317:4317"          # OTLP over gRPC receiver
#      - "4318:4318"     # OTLP over HTTP receiver
      - "9464:9464"          # Prometheus exporter
      - "8888:8888"          # metrics endpoint







